"""python -m unittest discover -s tests  (with PYTHONPATH=src)"""

from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path

from optim_jev.tools.jev_router import context as context_mod, journal, policy, rules as rules_mod, scan, tool, writer
from optim_jev.tools.jev_router.catalog import build_ladder


class FakeJev:
    def __init__(self, probabilities: dict[str, float] | None = None, fail: bool = False,
                 effort: dict[str, float] | None = None) -> None:
        self.probabilities = probabilities or {}
        self.effort = effort if effort is not None else {"medium": 1.0}
        self.fail = fail
        self.calls = 0
        self.questions: dict = {}
        self.state: dict = {}

    def ask(self, state, questions):
        self.calls += 1
        self.questions = questions
        self.state = state
        if self.fail:
            raise policy.JevCompactionError("down")
        return {"answers": {
            name: {"probabilities": self.effort if name == "effort" else self.probabilities} for name in questions
        }}


def project() -> Path:
    root = Path(tempfile.mkdtemp())
    for path, size in {
        "src/core/db.py": 5000,
        "src/core/pricing/engine.py": 9000,
        "src/api/auth.py": 800,
        "src/gen/pb.py": 7000,
        "tests/test_a.py": 300,
        "README.md": 200,
        "node_modules/x/y.js": 10,
    }.items():
        (root / path).parent.mkdir(parents=True, exist_ok=True)
        (root / path).write_text("x" * size)
    return root


REPLY = """```json
{"paths": {
  "src/core/": {"min": "opus", "why": "pricing engine; subtle invariants"},
  "src/api/": {"min": "sonnet", "why": "thin handlers"},
  "src/api/auth.py": {"min": "sonnet"},
  "src/gen/": {"min": "none", "why": "generated by protoc"},
  "tests/": {"min": "haiku", "delete": "opus"},
  "src/core/pricing/engine.py": {"min": "opus"},
  "bogus/": {"min": "haiku"}},
 "context": {"general": ["db/migrations needs opus"],
             "src/core/": ["prices are integer cents; never floats"],
             "src/gen/": ["regenerate with make proto"],
             "bogus/": ["dropped: not in the tree"]}}
```"""


class ScanAndInit(unittest.TestCase):
    def test_scan_stops_at_depth_and_skips_vendored(self):
        paths = {e.path for e in scan.scan(project(), 2)}
        self.assertIn("src/core/", paths)
        self.assertNotIn("src/core/pricing/", paths)
        self.assertFalse(any(p.startswith("node_modules") for p in paths))

    def test_init_keeps_only_tree_paths_and_drops_redundant_rules(self):
        root = project()
        req = {"project_dir": str(root), "options": {}, "session_model": "claude-opus-5-5"}
        checks = {"opus": {"id": "claude-opus-5-5", "available": True}, "sonnet": {"id": "", "available": True},
                  "haiku": {"id": "", "available": False}}
        tool.init_save_mode({**req, "reply": REPLY, "checks": checks})
        saved = json.loads((root / ".optim-jev/jev_router/rules.json").read_text())
        self.assertNotIn("notes", saved)
        models = {m["alias"]: m for m in json.loads((root / ".optim-jev/jev_router/models.json").read_text())}
        self.assertEqual((models["sonnet"]["id"], models["haiku"]["available"]), ("", False))
        context = context_mod.load(root)
        self.assertEqual(context.general, ("db/migrations needs opus",))
        self.assertEqual(sorted(context.paths), ["src/core/", "src/gen/"])
        self.assertEqual(sorted(saved["paths"]), ["src/api/", "src/core/", "src/gen/", "tests/"])
        self.assertEqual(saved["paths"]["src/gen/"]["write"], [])
        self.assertEqual(saved["paths"]["tests/"]["write"], ["sonnet", "opus"])  # haiku unavailable: floor moves up
        self.assertEqual(saved["paths"]["tests/"]["delete"], ["opus"])
        self.assertIn("!jev_router/rules.json", (root / ".optim-jev/.gitignore").read_text())
        render_answer = tool.render_mode({**req, "mode": "delegate"})
        self.assertNotIn("haiku", render_answer["tiers"])  # unavailable after the check
        self.assertNotIn("src/core/", render_answer["section"])  # no rules table in the prompt

    def test_unparseable_reply_raises(self):
        with self.assertRaises(ValueError):
            writer.parse_reply("no json here", [], build_ladder("claude-opus-5-5"), {})


class Writer(unittest.TestCase):
    ladder = build_ladder("claude-opus-5-5")
    tiers = {"haiku": 1, "sonnet": 2, "opus": 3}
    tree = [scan.Entry(p, 1, 1) for p in ("src/", "docs/", "tools/", "tests/")]

    def parse(self, reply: str):
        return writer.parse_reply(reply, self.tree, self.ladder, self.tiers)

    def test_scopes_are_open_to_every_model_unless_restricted(self):
        rules, _ = self.parse(
            '{"paths": {"src/": {"why": "core"}, "docs/": {"why": "guides", "min": "none"}, "tools/": {}}}'
        )
        self.assertEqual(rules.paths["src/"].write, ("haiku", "sonnet", "opus"))
        self.assertEqual(rules.paths["docs/"].write, ())
        self.assertNotIn("tools/", rules.paths)  # open and no reason: adds nothing

    def test_context_never_repeats_rules_json(self):
        _, context = self.parse(
            '{"paths": {"src/": {"why": "core logic", "min": "sonnet"}, "docs/": {"why": "guides"}},'
            ' "context": {"general": ["Documentation work only by sonnet or cheaper"],'
            '  "src/": ["needs opus here", "ids are integer cents"], "docs/": ["guides"]}}'
        )
        self.assertEqual(context.general, ("Documentation work only by sonnet or cheaper",))
        self.assertEqual(context.paths, {"src/": ("ids are integer cents",)})

    def test_prompt_carries_the_digest(self):
        text = writer.user_prompt([], "", self.ladder, ["src/a.py  does a thing"])
        self.assertIn("What the main files hold:\nsrc/a.py  does a thing", text)


class Digest(unittest.TestCase):
    def test_first_comment_and_names_not_contents(self):
        root = Path(tempfile.mkdtemp())
        (root / "src").mkdir()
        (root / "src/price.py").write_text(
            '"""Prices in integer cents."""\nSECRET = 1\n\ndef quote(x):\n    pass\n\nclass Engine:\n    pass\n'
        )
        (root / "src/api.ts").write_text("/** Thin HTTP handlers */\nexport function login() {}\nexport const router = 1;\n")
        (root / "README.md").write_text("# The shop\n\ntext\n")
        lines = scan.digest(root)
        self.assertIn("src/price.py  Prices in integer cents. · defines quote, Engine", lines)
        self.assertIn("src/api.ts  Thin HTTP handlers · defines login, router", lines)
        self.assertIn("README.md  The shop", lines)
        self.assertFalse(any("SECRET" in line for line in lines))

    def test_init_refuses_to_overwrite_without_force(self):
        root = project()
        req = {"project_dir": str(root), "options": {}, "session_model": "claude-opus-5-5"}
        self.assertIn("system", tool.scan_mode(req))
        tool.init_save_mode({**req, "reply": REPLY})
        self.assertIn("already has", tool.scan_mode(req)["refused"])
        self.assertIn("system", tool.scan_mode({**req, "force": True}))


class Rules(unittest.TestCase):
    known = ("haiku", "sonnet", "opus")

    def test_min_stands_in_for_write(self):
        rules = rules_mod.parse({"paths": {"a/": {"min": "sonnet"}, "b/": {"min": "none"}, "c/": {"min": "gpt"}}}, self.known)
        self.assertEqual(rules.paths["a/"].write, ("sonnet", "opus"))
        self.assertEqual(rules.paths["b/"].write, ())
        self.assertNotIn("c/", rules.paths)

    def test_validate_names_each_silent_failure(self):
        root = project()
        path = root / ".optim-jev/jev_router/rules.json"
        path.parent.mkdir(parents=True)
        self.assertEqual(rules_mod.validate(root, self.known), [])
        path.write_text('{"paths": {"a/": {"write": ["haiku",]}}}')
        self.assertIn("not valid JSON", rules_mod.validate(root, self.known)[0])
        path.write_text('{"paths": {"a/": {"write": ["Sonnet"]}, "b/": {"why": "x"}, "c/": {"write": ["opus"]}, "d/": {"min": "sonnet"}}}')
        problems = rules_mod.validate(root, self.known)
        self.assertEqual(len(problems), 2)
        self.assertIn("no model may write there", problems[0])
        self.assertIn('"b/"', problems[1])

    def test_section_tells_claude_how_to_keep_the_files(self):
        section = tool.render_mode({"project_dir": str(project()), "options": {}, "session_model": "claude-opus-5-5"})["section"]
        self.assertIn(".optim-jev/jev_router/rules.json", section)
        self.assertIn("Never write it in both", section)
        self.assertIn("haiku, sonnet, opus", section)

    def test_nearest_ancestor_wins(self):
        rules = rules_mod.parse({"paths": {"src/": {"write": ["opus"]}, "src/a/": {"write": ["haiku"]}}}, ("haiku", "sonnet", "opus"))
        self.assertEqual(rules_mod.resolve(rules, "src/a/b/c.py").write, ("haiku",))
        self.assertEqual(rules_mod.resolve(rules, "src/x.py").write, ("opus",))
        self.assertIsNone(rules_mod.resolve(rules, "docs/x.md"))

    def test_context_sections_load_only_for_planned_paths(self):
        ctx = context_mod.parse("# x\n## General\n- g1\n## `src/core/`\n- c1\n## docs/\n- d1\n")
        lines = context_mod.relevant(ctx, ["src/core/db/models.py"])
        self.assertEqual(lines, ["- g1", "src/core/:", "- c1"])
        self.assertEqual(context_mod.parse(context_mod.markdown(ctx)), ctx)


class Spawn(unittest.TestCase):
    def setUp(self):
        self.root = project()
        self.req = {"project_dir": str(self.root), "options": {}, "session_model": "claude-opus-5-5"}
        tool.init_save_mode({**self.req, "reply": REPLY})
        _, self.rules, self.ladder = tool._context(self.req)

    def pick(self, prompt, jev, ladder=None, escalated=None, **kw):
        ladder = ladder or self.ladder
        return policy.pick("task", prompt, self.rules, [], ladder, jev, str(self.root), escalated, **kw)

    def test_files_named_in_the_prompt_bind_the_choice(self):
        jev = FakeJev({"opus": 0.2, "sonnet": 0.7})
        result = self.pick(f"Add oauth to {self.root / 'src/api/auth.py'} and update README.md", jev)
        self.assertEqual([f.path for f in result.files], ["src/api/auth.py", "README.md"])
        self.assertEqual((result.model, result.source), ("sonnet", "jev"))
        self.assertEqual(sorted(jev.questions["model"]["criteria"]), ["opus", "sonnet"])

    def test_one_allowed_model_asks_jev_only_for_effort_and_blocked_files_are_named(self):
        jev = FakeJev({"haiku": 1.0}, effort={"high": 0.8, "low": 0.2})
        result = self.pick("Index src/core/db.py; regenerate src/gen/pb.py", jev)
        self.assertEqual((result.model, result.source, result.effort), ("opus", "rules", "high"))
        self.assertEqual(list(jev.questions), ["effort"])
        self.assertIn("xhigh", jev.questions["effort"]["criteria"])  # opus can be the answer
        self.assertIn("Never edit: src/gen/", policy.appendix(result, ["- prices are integer cents"], self.ladder))

    def test_jev_failure_falls_back_to_the_session_model(self):
        result = self.pick("Tidy tests/test_a.py", FakeJev(fail=True))
        self.assertEqual((result.model, result.source, result.jev_failed), ("opus", "fallback", "down"))

    def test_cap_keeps_jev_at_or_below_the_session_model(self):
        jev = FakeJev({"opus": 0.9, "sonnet": 0.06, "haiku": 0.04})
        result = self.pick("Fix a typo in README.md", jev, ladder=build_ladder("claude-sonnet-5-5"))
        self.assertEqual(sorted(jev.questions["model"]["criteria"]), ["haiku", "sonnet"])
        self.assertEqual(result.model, "sonnet")

    def test_escalated_files_start_a_model_up(self):
        jev = FakeJev({"haiku": 0.9, "sonnet": 0.1})
        result = self.pick("Fix README.md", jev, escalated={"README.md": 1})
        self.assertEqual((result.model, result.escalated), ("sonnet", 1))

    def test_escalation_keeps_the_effort_and_does_not_reask_it(self):
        jev = FakeJev({"haiku": 0.9, "sonnet": 0.1}, effort={"high": 1.0})
        result = self.pick("Fix README.md", jev, escalated={"README.md": {"levels": 1, "effort": "low"}})
        self.assertEqual((result.model, result.effort), ("sonnet", "low"))
        self.assertNotIn("effort", jev.questions)

    def test_escalation_stops_at_the_strongest_model(self):
        result = self.pick("Fix README.md", FakeJev({"opus": 1.0}), escalated={"README.md": {"levels": 5, "effort": "high"}})
        self.assertEqual((result.model, result.effort), ("opus", "high"))

    def test_xhigh_only_for_opus(self):
        jev = FakeJev({"sonnet": 0.9, "opus": 0.1}, effort={"xhigh": 0.9, "low": 0.1})
        result = self.pick("Fix README.md", jev)
        self.assertEqual((result.model, result.effort), ("sonnet", "high"))  # clamped
        no_opus = FakeJev({"sonnet": 1.0})
        self.pick("Fix README.md", no_opus, ladder=build_ladder("claude-sonnet-5-5"))
        self.assertNotIn("xhigh", no_opus.questions["effort"]["criteria"])

    def test_bad_effort_answer_keeps_the_model(self):
        jev = FakeJev({"opus": 0.2, "sonnet": 0.8}, effort={})
        result = self.pick("Fix README.md", jev)
        self.assertEqual((result.model, result.source, result.effort), ("sonnet", "jev", None))

    def test_input_is_priority_ordered_and_trimmed_from_the_bottom(self):
        jev = FakeJev({"sonnet": 1.0})
        recent = [f"earlier prompt {i} " + "x" * 400 for i in range(4)]
        result = self.pick("Fix README.md " + "y" * 3000, jev, recent=recent, budget=900)
        self.assertTrue(result.trimmed)
        keys = list(jev.state)
        self.assertEqual(keys[:3], ["subagent_task", "files", "models"])
        self.assertLess(len(jev.state.get("recent_user_inputs", [])), 4)  # oldest dropped first
        self.assertLessEqual(result.input_tokens_est, 900)

    def test_over_budget_hands_the_decision_to_claude(self):
        jev = FakeJev({"sonnet": 1.0})
        result = self.pick("Fix README.md", jev, budget=50)
        self.assertEqual(jev.calls, 0)
        self.assertIn("Reply with only a JSON object", result.ask_claude)
        decided = self.pick("Fix README.md", jev, decided={"model": "sonnet", "effort": "low"})
        self.assertEqual((decided.model, decided.effort, decided.source), ("sonnet", "low", "claude"))
        bogus = self.pick("Fix README.md", jev, decided={"model": "gpt", "effort": "huge"})
        self.assertEqual((bogus.model, bogus.effort), ("opus", None))  # session model, default effort

    def test_spawn_mode_logs_and_returns_the_appendix(self):
        answer = tool.spawn_mode({**self.req, "session_id": "s", "description": "core index", "prompt": "Index src/core/db.py"})
        self.assertEqual(answer["model"], "opus")
        self.assertEqual((answer["source"], answer["escalated"]), ("rules", 0))
        self.assertIn("prices are integer cents", answer["appendix"])
        self.assertIn("core index → opus", journal.why(journal.read(self.root, "s"), "s"))
        self.assertTrue((Path(self.root) / ".optim-jev" / "logs" / "jev_router" / "s.jsonl").is_file())


class Report(unittest.TestCase):
    def test_table_columns_align_and_total_is_ruled_off(self):
        from optim_jev.core import report
        lines = report.table("T", ("Item", "USD"), [("a", "$1.00"), ("longer item", "$12.50")], right=(1,), total=("Net saved", "$13.50"))
        self.assertEqual(lines[0], "▸ T")
        self.assertEqual(len({len(line) for line in lines[1:]}), 1)
        self.assertEqual(lines[-3][0], "├")  # rule above the total
        self.assertTrue(lines[-2].startswith("│ Net saved"))
        self.assertTrue(lines[4].endswith("  $1.00 │"))  # numbers right-aligned


class Journal(unittest.TestCase):
    def test_stats(self):
        root = str(project())
        journal.append(root, "s", {"kind": "spawn", "current": "opus", "model": "haiku", "source": "jev"})
        journal.append(root, "s", {"kind": "outcome", "escalations": [{"from": "haiku", "to": "sonnet"}], "denials": 2})
        from optim_jev.tools.jev_router.catalog import load_catalog
        journal.append(root, "other", {"kind": "spawn", "current": "opus", "model": "opus", "source": "jev"})
        claude = [
            {"kind": "turn", "agent_id": None, "model": "claude-opus-5-5", "input_tokens": 10},
            {"kind": "spawned", "agent_id": "a1", "model": "claude-haiku-4-5"},
            {"kind": "turn", "agent_id": "a1", "model": "claude-haiku-4-5", "input_tokens": 1_000_000},
        ]
        text = journal.stats(journal.read(root, "s"), load_catalog(), claude)
        rows = {line.split("│")[1].strip(): line for line in text.splitlines() if line.startswith("│")}
        self.assertIn("1 (100%)", rows["on haiku"])
        self.assertIn("$1.00", rows["Subagents on routed models"])
        self.assertIn("$5.00", rows["Same work on claude-opus-5-5"])
        self.assertIn("$4.00", rows["Net saved"])
        self.assertIn("2", rows["Denied writes"])
        widths = {len(line) for line in text.splitlines()[1:12] if line[:1] in "┌│├└"}
        self.assertEqual(len(widths), 1)  # every line of a table is the same width


if __name__ == "__main__":
    unittest.main()
