"""python -m unittest discover -s tests  (with PYTHONPATH=src)"""

from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path

from optim_jev.tools.jev_router import context as context_mod, journal, policy, rules as rules_mod, scan, tool, writer
from optim_jev.tools.jev_router.catalog import build_ladder


class FakeJev:
    def __init__(self, probabilities: dict[str, float] | None = None, fail: bool = False) -> None:
        self.probabilities = probabilities or {}
        self.fail = fail
        self.calls = 0
        self.questions: dict = {}

    def ask(self, state, questions):
        self.calls += 1
        self.questions = questions
        if self.fail:
            raise policy.JevCompactionError("down")
        return {"answers": {name: {"probabilities": self.probabilities} for name in questions}}


def project() -> Path:
    root = Path(tempfile.mkdtemp())
    for path, size in {
        "src/core/db.py": 5000,
        "src/core/pricing/engine.py": 9000,
        "src/api/auth.py": 800,
        "src/gen/pb.py": 7000,
        "tests/test_a.py": 300,
        "README.md": 200,
        "node_modules/x/y.js": 10,
    }.items():
        (root / path).parent.mkdir(parents=True, exist_ok=True)
        (root / path).write_text("x" * size)
    return root


REPLY = """```json
{"paths": {
  "src/core/": {"min": "opus", "why": "pricing engine; subtle invariants"},
  "src/api/": {"min": "sonnet", "why": "thin handlers"},
  "src/api/auth.py": {"min": "sonnet"},
  "src/gen/": {"min": "none", "why": "generated by protoc"},
  "tests/": {"min": "haiku", "delete": "sonnet"},
  "src/core/pricing/engine.py": {"min": "opus"},
  "bogus/": {"min": "haiku"}},
 "context": {"general": ["db/migrations needs opus"],
             "src/core/": ["prices are integer cents; never floats"],
             "src/gen/": ["regenerate with make proto"],
             "bogus/": ["dropped: not in the tree"]}}
```"""


class ScanAndInit(unittest.TestCase):
    def test_scan_stops_at_depth_and_skips_vendored(self):
        paths = {e.path for e in scan.scan(project(), 2)}
        self.assertIn("src/core/", paths)
        self.assertNotIn("src/core/pricing/", paths)
        self.assertFalse(any(p.startswith("node_modules") for p in paths))

    def test_init_keeps_only_tree_paths_and_drops_redundant_rules(self):
        root = project()
        req = {"project_dir": str(root), "options": {}, "session_model": "claude-opus-5-5"}
        checks = {"opus": {"id": "claude-opus-5-5", "available": True}, "sonnet": {"id": "", "available": True},
                  "haiku": {"id": "", "available": False}}
        tool.init_save_mode({**req, "reply": REPLY, "checks": checks})
        saved = json.loads((root / ".optim-jev/jev_router/rules.json").read_text())
        self.assertNotIn("notes", saved)
        models = {m["alias"]: m for m in json.loads((root / ".optim-jev/jev_router/models.json").read_text())}
        self.assertEqual((models["sonnet"]["id"], models["haiku"]["available"]), ("", False))
        context = context_mod.load(root)
        self.assertEqual(context.general, ("db/migrations needs opus",))
        self.assertEqual(sorted(context.paths), ["src/core/", "src/gen/"])
        self.assertEqual(sorted(saved["paths"]), ["src/api/", "src/core/", "src/gen/", "tests/"])
        self.assertEqual(saved["paths"]["src/gen/"]["write"], [])
        self.assertEqual(saved["paths"]["tests/"]["write"], ["sonnet", "opus"])  # haiku unavailable: floor moves up
        self.assertIn("!jev_router/rules.json", (root / ".optim-jev/.gitignore").read_text())
        render_answer = tool.render_mode({**req, "mode": "delegate"})
        self.assertNotIn("haiku", render_answer["tiers"])  # unavailable after the check
        self.assertNotIn("src/core/", render_answer["section"])  # no rules table in the prompt

    def test_unparseable_reply_raises(self):
        with self.assertRaises(ValueError):
            writer.parse_reply("no json here", [], build_ladder("claude-opus-5-5"), {})


class Rules(unittest.TestCase):
    def test_nearest_ancestor_wins(self):
        rules = rules_mod.parse({"paths": {"src/": {"write": ["opus"]}, "src/a/": {"write": ["haiku"]}}}, ("haiku", "sonnet", "opus"))
        self.assertEqual(rules_mod.resolve(rules, "src/a/b/c.py").write, ("haiku",))
        self.assertEqual(rules_mod.resolve(rules, "src/x.py").write, ("opus",))
        self.assertIsNone(rules_mod.resolve(rules, "docs/x.md"))

    def test_context_sections_load_only_for_planned_paths(self):
        ctx = context_mod.parse("# x\n## General\n- g1\n## `src/core/`\n- c1\n## docs/\n- d1\n")
        lines = context_mod.relevant(ctx, ["src/core/db/models.py"])
        self.assertEqual(lines, ["- g1", "src/core/:", "- c1"])
        self.assertEqual(context_mod.parse(context_mod.markdown(ctx)), ctx)


class Spawn(unittest.TestCase):
    def setUp(self):
        self.root = project()
        self.req = {"project_dir": str(self.root), "options": {}, "session_model": "claude-opus-5-5"}
        tool.init_save_mode({**self.req, "reply": REPLY})
        _, self.rules, self.ladder = tool._context(self.req)

    def pick(self, prompt, jev, ladder=None, escalated=None):
        ladder = ladder or self.ladder
        return policy.pick("task", prompt, self.rules, [], ladder, jev, str(self.root), escalated)

    def test_files_named_in_the_prompt_bind_the_choice(self):
        jev = FakeJev({"opus": 0.2, "sonnet": 0.7})
        result = self.pick(f"Add oauth to {self.root / 'src/api/auth.py'} and update README.md", jev)
        self.assertEqual([f.path for f in result.files], ["src/api/auth.py", "README.md"])
        self.assertEqual((result.model, result.source), ("sonnet", "jev"))
        self.assertEqual(sorted(jev.questions["model"]["criteria"]), ["opus", "sonnet"])

    def test_one_allowed_model_skips_jev_and_blocked_files_are_named(self):
        jev = FakeJev({"haiku": 1.0})
        result = self.pick("Index src/core/db.py; regenerate src/gen/pb.py", jev)
        self.assertEqual((result.model, result.source, jev.calls), ("opus", "rules", 0))
        self.assertIn("Never edit: src/gen/", policy.appendix(result, ["- prices are integer cents"], self.ladder))

    def test_jev_failure_falls_back_to_the_session_model(self):
        result = self.pick("Tidy tests/test_a.py", FakeJev(fail=True))
        self.assertEqual((result.model, result.source, result.jev_failed), ("opus", "fallback", "down"))

    def test_cap_keeps_jev_at_or_below_the_session_model(self):
        jev = FakeJev({"opus": 0.9, "sonnet": 0.06, "haiku": 0.04})
        result = self.pick("Fix a typo in README.md", jev, ladder=build_ladder("claude-sonnet-5-5"))
        self.assertEqual(sorted(jev.questions["model"]["criteria"]), ["haiku", "sonnet"])
        self.assertEqual(result.model, "sonnet")

    def test_escalated_files_start_a_model_up(self):
        jev = FakeJev({"haiku": 0.9, "sonnet": 0.1})
        result = self.pick("Fix README.md", jev, escalated={"README.md": 1})
        self.assertEqual((result.model, result.escalated), ("sonnet", 1))

    def test_spawn_mode_logs_and_returns_the_appendix(self):
        answer = tool.spawn_mode({**self.req, "session_id": "s", "description": "core index", "prompt": "Index src/core/db.py"})
        self.assertEqual(answer["model"], "opus")
        self.assertIn("prices are integer cents", answer["appendix"])
        self.assertIn("core index → opus", journal.why(journal.read(self.root, "s"), "s"))
        self.assertTrue((Path(self.root) / ".optim-jev" / "logs" / "jev_router" / "s.jsonl").is_file())


class Journal(unittest.TestCase):
    def test_stats(self):
        root = str(project())
        journal.append(root, "s", {"kind": "spawn", "current": "opus", "model": "haiku", "source": "jev"})
        journal.append(root, "s", {"kind": "outcome", "escalations": [{"from": "haiku", "to": "sonnet"}], "denials": 2})
        from optim_jev.tools.jev_router.catalog import load_catalog
        journal.append(root, "other", {"kind": "spawn", "current": "opus", "model": "opus", "source": "jev"})
        claude = [
            {"kind": "turn", "agent_id": None, "model": "claude-opus-5-5", "input_tokens": 10},
            {"kind": "spawned", "agent_id": "a1", "model": "claude-haiku-4-5"},
            {"kind": "turn", "agent_id": "a1", "model": "claude-haiku-4-5", "input_tokens": 1_000_000},
        ]
        text = journal.stats(journal.read(root, "s"), load_catalog(), claude)
        self.assertIn("haiku 100%", text)
        self.assertIn("on their routed models (measured)   $1.00", text)
        self.assertIn("same tokens on claude-opus-5-5 (est.)   $5.00", text)
        self.assertIn("net saved", text)
        self.assertIn("denied writes: 2", text)


if __name__ == "__main__":
    unittest.main()
